# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44807f852910334da8d5e89db2b1e66ab13cd23bdb9df1b735e4ebaf31d5682b62dc1982244bb191a7c9a1ff583ba7fc98c83b922045ef7a9b03d692fbb1c649

test:
  secret_key_base: 9e81c18fd1cc27743720de9b16e7183c1cbf13a9604ddec32ba8117a3a61544a9f560684669371a23e1e02a7fe428d6e9f9eef89025f14ebae894e92cd53ad25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
